version: '3.8'

services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hyteno_fullstack_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3100:3000' # Host:Container
    networks:
      - app-network
    command: >
      sh -c "
        yarn prisma migrate deploy &&
        yarn prisma db seed &&
        node dist/main
      "

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
