services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: hyteno_fullstack_todo
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  # Backend service
  backend:
    build: .
    image: hyteno-todo-api
    ports:
      - "3100:3000" # Host : Container
    depends_on:
      - database 
    env_file:
      - .env
    restart: unless-stopped

volumes:
  database:
    name: hyteno_fullstack_todo_db
