services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hyteno_fullstack_todo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend service
  backend:
    build: .
    ports:
      - "3100:3000" # Host : Container
    depends_on:
      - database # Ensure that the backend service starts after the database service is up and running
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db-data:
