# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = hyteno_fullstack_todo 
ENV POSTGRES_USER = myuser
ENV POSTGRES_PASSWORD = mypassword

# Expose the PostgreSQL port
EXPOSE 5432